from django.core.management.base import BaseCommand
from django.contrib.auth.models import Group
from DjangoHUDApp.models import Product, Warehouse, Stock
from DjangoHUDApp.models import Product, ProductCategory, ProductUsage, Warehouse, Stock

class Command(BaseCommand):
    help = 'Creates all the product instances for doriforika created'

    def handle(self, *args, **options):
        # Retrieve the "ΔΟΡΥΦΟΡΙΚΑ" group
        group_doriforika, created = Group.objects.get_or_create(name='ΔΟΡΥΦΟΡΙΚΑ')

        category_kamia_epilogi = ProductCategory.objects.get(name='ΚΑΜΙΑ ΕΠΙΛΟΓΗ')
        usage_doriforika = ProductUsage.objects.get(name='ΔΟΡΥΦΟΡΙΚΑ')
        
        doriforika_products = [
            {"BATCH NO.": 751, "NAME": "ΤΕΧΝΙΚΑ ΕΓΧΕΙΡΙΔΙΑ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 798, "NAME": "Τ.Δ.FD177/RACAL/PRM4720B", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 1005, "NAME": "MINI LINK ROUTERBOARD 2X16 db(MIKROTIK)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 1509, "NAME": "ΤΡΟΦΟΔΟΤΙΚΟ ΜΕΚΑΛΩΔΙΟ ΣΥΝΔΕΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 1521, "NAME": "ΚΑΛΩΔΙΟ ΤΕΤΡΑΠΟΛΙΚΟ", "UNITS OF MEASUREMENT": "Μέτρα", "QUANTITY": 3625},
            {"BATCH NO.": 1522, "NAME": "ΑΤΡΑΚΤΟΙ DR-8", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 13},
            {"BATCH NO.": 1569, "NAME": "ΑΤΡΑΚΤΟΙ ΠΡΟΤΟΝΩΝ RL-28", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 1621, "NAME": "ΦΟΡΤΙΣΤΗΣ ΜΠΑΤΑΡΙΑΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 20},
            {"BATCH NO.": 1622, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΤΕΡΜΑΤΙΚΟ THURAYA MAINSTREAM", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 1623, "NAME": "MODEM", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 1624, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΤΗΛΕΦΩΝΟ IRIDIUM 9575", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 1627, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΤΗΛΕΦΩΝΟ IRIDIUM 9555", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 5968, "NAME": "ΣΥΣΤΗΜΑ ΔΟΡΥΦΟΡΙΚΟΥ ΤΕΡΜΑΤΙΚΟΥ ΥΨΗΛΩΝ ΡΥΘΜ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 11},
            {"BATCH NO.": 5976, "NAME": "ΔΟΡΥΦΟΡΙΚΟΣ ΕΝΙΣΧΥΤΗΣ 4W ACTOX", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 5978, "NAME": "LNB ΔΟΡΥΦΟΡΙΚΟΣ ΔΕΚΤΗΣ SAT-4", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 5},
            {"BATCH NO.": 5986, "NAME": "UBIQUITI AF-5XHD AIRFIBER 5XH MINI LINK 20-100 ΧΛ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 5987, "NAME": "ΚΕΡΑΙΑ ROCKET DISH 972MM RADOME MINI LINK 100-2", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 5988, "NAME": "ΖΕΥΓΟΣ ΜΙΚΡ/ΚΩΝ ΣΥΣΤΗΜ.(ROUTERBOARD RBLHG)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 5993, "NAME": "ROUTERBOARD CCR1016 12G", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 5995, "NAME": "MIKROTIK RB1100AHX4 ROUTER", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 22},
            {"BATCH NO.": 5999, "NAME": "Σ/Α HF/SSB ΦΟΡΗΤΟΣ ΚΑΝΟΝΙΚΗΣ ΙΣΧΥΟΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 6049, "NAME": "ΚΑΛΩΔΙΟ ΔΙΑΣΥΝΔΕΣΗΣ ΔΕΔΟΜΕΝΩΝ CBF 305/V3", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 5},
            {"BATCH NO.": 6050, "NAME": "ΚΑΛΩΔΙΑ ΔΙΑΣΥΝΔΕΣΗΣ ΔΕΔΟΜΕΝΩΝ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 6052, "NAME": "ΚΑΛΩΔ ΑΝΑΜΕΤ CBF-209", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 13},
            {"BATCH NO.": 6054, "NAME": "Σ/Α HF/SSB ΟΧΗΜΑΤΟΣ ΚΑΝ/ΥΨΗΛ ΙΣΧΥΟΣ TRC-3600", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 6132, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΤΕΡΜΑΤΙΚΟ IRIDIUM 9505A", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 6151, "NAME": "ΔΙΑΧΩΡΙΣΤΙΚΗ ΟΡΙΟΛΩΡ 10", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 6255, "NAME": "Σ/Α ΦΟΡΗΤΟΣ ΧΑΜΗΛΗΣ ΙΣΧΥΟΣ PRC-9200", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 6262, "NAME": "Σ/Α ΑΝ /PRC-77", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6268, "NAME": "ΗΛΕΚΤΡΙΚΟΣ ΠΙΝΑΚΑΣ ΠΛΗΡΗΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6269, "NAME": "ΚΑΤΑΝΕΜΗΤΗΣ ΞΩΤ. ΧΩΡΟΥ ΣΤΕΓΑΝΟΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6270, "NAME": "ΙΚΡΙΩΜΑ ΕΞΟΠΛ. RACK 22''U ΜΕ ΔΥΟ(2) PATCH PANEL 2", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6276, "NAME": "ΣΥΛΛΟΓΗ ΠΡΟΣΔΕΣΕΩΝ ΚΛΩΒΟΥ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6277, "NAME": "ΠΑΓΚΟΣ ΕΡΓΑΣΙΑΣ MDF 170X50X75", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6278, "NAME": "ΣΥΛΛΟΓΗ ΓΕΙΩΣΕΩΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6279, "NAME": "ΒΑΣΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΔΟΡΥΦ. ΚΕΡΑΙΑΣ FLYAWAY", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6280, "NAME": "ROUTER MIKROTIK CCR 1036-8G-2S", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 15},
            {"BATCH NO.": 6281, "NAME": "ΜΗΧΑΝΙΣΜΟΣ ΡΥΘΜΙΣΗΣ ΠΟΛΩΣΗΣ ΚΕΡΑΙΑΣ FLYAWAY", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6282, "NAME": "ΜΗΧΑΝΙΣΜΟΣ ΚΙΝΗΣΗΣ ΚΑΤΆ ΑΖΙΜΟΥΘΙΟ ΚΕΡΑΙΑΣ FL", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6283, "NAME": "ΜΗΧΑΝΙΣΜΟΣ ΑΝΥΨΩΣΗΣ ΚΕΡΑΙΑΣ FLYAWAY", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 6284, "NAME": "ΚΑΛΩΔΙΟ ΦΟΡΤΩΣΗΣ ΔΕΔΟΜ. FILL DEVICE DS-101", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 20},
            {"BATCH NO.": 7700, "NAME": "ΣΗΜΕΙΟ ΠΡΟΣΒΑΣΗΣ 5GHZ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 7701, "NAME": "ΠΟΜΠΟΔΕΚΤΗΣ MSMS", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7702, "NAME": "ΠΟΜΠΟΔΕΚΤΗΣ GBE-LR", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7703, "NAME": "TRANSCEIVER UBIQUITI R5AC LITE (ΠΟΜΠΟΔΕΚΤΗΣ)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 7704, "NAME": "UBIQUITI AF5XHD AIRFIBER 5XH (ΠΟΜΠΟΔΕΚΤΗΣ)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 7705, "NAME": "ΠΟΜΠΟΔΕΚΤΗς RB MetalLG-52SHP can", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7706, "NAME": "RD.RD2 (ΠΡΟΣΤΑΤΕΥΤΙΚΟ ΚΑΛΥΜΜΑ)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 7707, "NAME": "ΠΟΜΠΟΔΕΚΤΗς RBLHG-5HPnD-XL", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7708, "NAME": "ΠΟΜΠΟΔΕΚΤΗΣ RBLHYG-2nD-XL", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 5},
            {"BATCH NO.": 7709, "NAME": "ΔΙΠΛΕΚΤΗΣ ΧΑΜΗΛΗΣ ΜΠΑΝΤΑΣ AF-11-DNP-L", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 7710, "NAME": "ΔΙΠΛΕΚΤΗΣ ΧΑΜΗΛΗΣ ΜΠΑΝΤΑΣ AF-11-DVP-H", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 7711, "NAME": "ΠΟΜΠΟΔΕΚΤΗΣ AF-11", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7712, "NAME": "ΑΝΑΜΕΤΑΔΟΤΗΣ WIFI PE 505X", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7895, "NAME": "ΕΝΙΣΧΥΤΗΣ 4WATT", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7896, "NAME": "ΕΝΙΣΧΥΤΗΣ 16  WATT", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7898, "NAME": "ΚΕΡΑΙΑ 1,2 FLY AWAY 13,750-14,5 GHZ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 7899, "NAME": "ΔΕΚΤΗΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7900, "NAME": "ΣΥΣΤΗΜΑ ΠΑΡΟΧΗΣ ΡΕΥΜΑΤΟΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7901, "NAME": "Η/Ζ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7902, "NAME": "ΚΕΡΑΙΟΣΥΣΤΗΜΑ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7903, "NAME": "ΣΥΣΚΕΥΗ ΔΡΟΜΟΛΟΓΗΣΗΣ ΠΑΚΕΤΩΝ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7904, "NAME": "ΗΛΕΚΤΡΟΠΑΡΑΓΩΓΟ ΖΕΥΓΟΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 7905, "NAME": "ΔΡΟΜΟΛΟΓΗΤΗΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7906, "NAME": "ΔΙΑΜΟΡΦΩΤΗΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7907, "NAME": "ΙΚΡΙΩΜΑ ΤΟΠΟΘΕΤΗΣΗΣ ΥΛΙΚΩΝ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7908, "NAME": "ΓΕΝΝΗΤΡΙΑ ΡΕΥΜΑΤΟΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7909, "NAME": "ΦΙΛΤΡΟ ΣΥΧΝΟΤΗΤΩΝ ΔΟΡΥΦ. ΚΕΡΑΙΑΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7912, "NAME": "ΚΑΛΩΔΙΟ UTP 6X1,525 METΡΑ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7921, "NAME": "ΔΕΚΤΗΣ ΠΑΓΚΟΣΜΙΟΥ ΛΗΨΕΩΣ S-2000", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 7928, "NAME": "ΠΕΔΙΟΜΕΤΡΟ Η30 EVOLUTION", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7929, "NAME": "ΞΗΡΟ ΣΤΟΙΧΕΙΟ ΧΡΟΝΟΜΕΤΡΟΥ (LS 14250)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 13},
            {"BATCH NO.": 7930, "NAME": "ΠΡΟΣΑΡΜΟΣΤΙΚΕΣ ΔΙΑΤΑΞΕΙΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7931, "NAME": "ΣΕΤ ΦΙΛΤΡΑ ΖΩΝΗΣ ΑΠΟΚΟΠΗΣ ΣΥΧΝ/ΤΩΝ ΚΕΡΑΙΟΣΥΣΤ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 32},
            {"BATCH NO.": 7932, "NAME": "ΠΟΜΠΟΔΕΚΤΗΣ ΚU BAND 16 W ANASAT TRANCEIVER", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7933, "NAME": "ΔΟΡΥΦΟΡΙΚΕΣ ΚΕΡΑΙΕΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7935, "NAME": "MIKROWAVE W6 TO COAXIAL ADAPTOR", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7936, "NAME": "STF ETHERNET S-RJ01 MICROTIK", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7937, "NAME": "ΠΟΜΠΟΔΕΚΤΗΣ UBIQUITI R5AC-LITE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 7938, "NAME": "ΠΟΜΠΟΔΕΚΤΗΣ UBIQUITI BULLET DUAL BAND", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7939, "NAME": "ΚΑΛΩΔΙΟ ΔΡΟΜΟΛ. UBIQUITI TOUTCE CABLE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7941, "NAME": "ΚΕΡΑΙΑ RD-5G30", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 7942, "NAME": "ΒΑΣΗ ΚΕΡΑΙΑΣ MOUNT MICROTIC LITE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7944, "NAME": "ΣΥΣΚΕΥΗ ΕΝΙΣΧΥΣΗΣ ΣΗΜΑΤΟΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 7945, "NAME": "ΣΥΣΚΕΥΗ ΛΗΨΗΣ ΔΟΡΥΦΟΡΙΚΟΥ ΣΗΜΑΤΟΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7946, "NAME": "ΚΕΡΑΙΑ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7947, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΠΙΑΤΟ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7948, "NAME": "ΣΥΣΚΕΥΗ ΜΕΤΑΔΟΣΗΣ ΔΟΡΥΦΟΡΙΚΗΣ ΕΚΠΟΜΠΗΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7949, "NAME": "RACK", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 7950, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΜΟΝΤΕΜ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7951, "NAME": "ΔΟΡΥΦΟΡΙΚΟΣ ΕΝΙΣΧΥΤΗΣ 50W Advetec Wirel", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7952, "NAME": "ΔΟΡΥΦΟΡΙΚΟΣ ΕΝΙΣΧΥΤΗΣ 220V-50W", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7954, "NAME": "ΔΟΡΥΦΟΡΙΚΟΣ ΕΝΙΣΧΥΤΗΣ 24V-8W", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7959, "NAME": "ΤΡΟΦΟΔΟΤΙΚΟ ΜΙΚΡΟΚΥΜΜΑΤΙΚΟΥ ΡΟΕ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 20},
            {"BATCH NO.": 7971, "NAME": "ΕΝΙΣΧΥΤΗΣ 24V-8W", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7973, "NAME": "ΜΕΜΒΡΑΝΗ FEEDHORN ΚΕΡΑΙΑ 1,8Μ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 7982, "NAME": "ΕΠΕΞΕΡΓΑΣΤΗΣ ΕΛΕΓΧΟΥ ΚΕΡΑΙΑΣ RC3000", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7983, "NAME": "ΚΕΡΑΙΑ MIKROTIK METAL OMNI DIRECTIONAL", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7984, "NAME": "ΒΑΣΗ ΚΕΡΑΙΑΣ ΙΝΟΧ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 11},
            {"BATCH NO.": 7986, "NAME": "ΠΟΛΥΚΑΤΕΥΘΥΝΤΙΚΗ ΚΕΡΑΙΑ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 11},
            {"BATCH NO.": 7987, "NAME": "ΕΠΕΞΕΡΓΑΣΤΗΣ ΤΥΠΟΥ FDMA DMD20 IF", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7988, "NAME": "ΤΡΟΦΟΔΟΤΙΚΟ ΤΥΠΟΥ FDMA DMD20 IF", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 4},
            {"BATCH NO.": 7989, "NAME": "ΒΑΘΜΙΔΑ ΤΡΟΦ.ΔΟΡΥΦ.ΠΕΔΙΟΜ.PROMAX TV EXPLORE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 7990, "NAME": "ΠΛΑΚΕΤΑ ΔΙΑΜΟΡΦ.ΣΗΜΑΤΟΣ.ΔΟΡΥΦ.ΠΕΔΙΟΜΕΤΡΟΥ P", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7991, "NAME": "VIDEO CODEC UNIT ΔΟΡΥΦ.ΠΕΔΙΟΜ.PROMAX HD RANG", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7992, "NAME": "TV SAT ANALYZER UNIT ΔΟΡΥΦ.ΠΕΔΙΟΜ.PROMAX HD R", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7993, "NAME": "LNB", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 9},
            {"BATCH NO.": 7995, "NAME": "ΤΡΟΦΟΔΟΤΙΚΟ ΕΞΟΔΟΥ MDX 420", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7996, "NAME": "ΠΛΑΚΕΤΑ ΕΚΠΟΜΠΗΣ MDX 420", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7997, "NAME": "LNB (APPENDIX)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 7998, "NAME": "ΣΥΣΣΩΡΕΥΤΗΣ MDX-420 SKYWIRE TDMA", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 5},
            {"BATCH NO.": 7999, "NAME": "ΒΑΘΜΙΔΑ ΨΥΞΗΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8051, "NAME": "ALGA MICROWAVE ALTX-LITE-KU-10BUC 10W 24VDCE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8052, "NAME": "ALGA MICROWAVE ALTX-LITE-KU-16BUC 16W 48VDCE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8053, "NAME": "ΗΛΕΚΤΡΟΛΟΓΙΚΟ ΚΥΤΙΟ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 30},
            {"BATCH NO.": 8054, "NAME": "SMW SWEDISH MICROWAVE SINGLE KU BAND PLL LNB", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8056, "NAME": "ALGA MICROWAVE ALTX-LITE-KU-8BUC 8W 48VDCEΝΙΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8057, "NAME": "ALGA MICROWAVE ALTX-LITE-KU-8BUC 8W 24VDCEΝΙ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8134, "NAME": "ΚΑΛΩΔΙΟ WD-1TT", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 20},
            {"BATCH NO.": 8135, "NAME": "FLEXIBLE WG 2.00M", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8245, "NAME": "ΕΝΙΣΧΥΤΗΣ ALTX-LIKE-KU-16W 24/48", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8246, "NAME": "MODEM DMD 20 LB ST HARDW.UPGRADE KIT", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8253, "NAME": "UBIQUITI ROCKET AIRMAX AP-CPE M5", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 16},
            {"BATCH NO.": 8254, "NAME": "NET UBIQUITI RAD-2RD RADOME", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 8282, "NAME": "NOTEBOOK DELL LATITUDE E5500", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 8288, "NAME": "H/Υ DELL OPTIPL 780DT/E8400/2GB", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8311, "NAME": "NETMETAL 5 2xRPSMA 2000mW", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8342, "NAME": "ΚΑΛΩΔΙΟ ΜΕΤΑΦΟΡΑΣ ΔΕΔΟΜΕΝΩΝ Σ/Α HF", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 8347, "NAME": "IC-F3022 EUR-02 Π/Δ (W/BP-232N) ICOM", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 5},
            {"BATCH NO.": 8354, "NAME": "ROUTER CISCO 2901+2FXS", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8356, "NAME": "H/Z 6 KVA CGM 7500DES", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8357, "NAME": "ΔΟΡΥΦΟΡΙΚΟ MODEM IP-TDMA MDX-420", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8360, "NAME": "UPS ΤΥΠΟΥ RACK ΜΕ ΜΠΑΤΑΡΙΕΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8375, "NAME": "MODEM DMD 20 RADYNE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 8376, "NAME": "ΚΕΡΑΙΑ 1,80 KU BAND VSAT", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8378, "NAME": "HP NOTEBOOK NX 7400i", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8384, "NAME": "NERAWORLDPHONE OFFICE BASK", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8387, "NAME": "ΕΝΙΣΧΥΤΗΣ 200W E2V", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8389, "NAME": "ΑΣΥΡΜΑΤΙΚΟΙ ΕΝΙΣΧΥΤΕΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8391, "NAME": "ΤΡΟΦΟΔΟΤΙΚΟ ΓΙΑ BUC16W", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8392, "NAME": "ΣΥΣΤΗΜΑ ΑΔΙΑΛΛΕΙΠΤΗΣ ΛΕΙΤΟΥΡ UPS", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 8394, "NAME": "ΜΗΧΑΝ. ΥΠΟΒΟΗΘΗΣΗΣ ΑΝΥΨ.ΔΟΡΥΦ.ΚΕΡΑΙΑΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8395, "NAME": "UBNT ROCKETDISH 30 DBI 5GHZ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 6},
            {"BATCH NO.": 8399, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΤΗΛ THURAYA XT PRO", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 10},
            {"BATCH NO.": 8429, "NAME": "UBIQUITI 11FX HIGH BRAND DUPLEXEUR", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8430, "NAME": "NET UBIQUITI RP-5AC 5GHZ GEN 2", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8431, "NAME": "UBNT RAD RD 3 RADOME (ΚΑΛΥΜΜΑ)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 22},
            {"BATCH NO.": 8437, "NAME": "NET UBIQUITI AF-5X HD 500MBPS", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 9},
            {"BATCH NO.": 8438, "NAME": "NET UBIQUITI AF-5G34-S45", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 15},
            {"BATCH NO.": 8439, "NAME": "NET UBIQUITI AF-11FX HIGH BRAND", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8440, "NAME": "NET UBIQUITI AF-11G35", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8442, "NAME": "NET UBIQUITI RAD-RD3", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8443, "NAME": "NET UBIQUITI EP-R6", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 8503, "NAME": "ΔΡΟΜΟΛΟΓΗΤΗΣ ROUTER", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8517, "NAME": "X-BAND FEEDHORN", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8518, "NAME": "ACORD BUC 40W", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 7},
            {"BATCH NO.": 8520, "NAME": "ΦΙΛΤΡΟ ΛΗΨΗΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8522, "NAME": "ΚΑΛ. UTP CAT5e ΜΟΝΟΚΛΩΝΟ (305Μ)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 8523, "NAME": "ΚΕΡΑΙΑ RX/TX 2.4 PRODELIN", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8530, "NAME": "UBNT AM-5G20-90 ΚΕΡΑΙΑ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8533, "NAME": "UBNT AM-5G19-120", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8536, "NAME": "ΤΗΛΕΦΩΝΙΚΟ ΚΕΝΤΡΟ ΚΧ-ΤD", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8540, "NAME": "TDR CABLE TELESCOUT TS90", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8541, "NAME": "UPS ΙΚΡΙΜΑΤΙΚΟΥ ΤΥΠΟΥ 3KVA", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8542, "NAME": "ΜΕΤΑΛ.ΙΚΡΙΩΜΑΤΙΚΟ 19'' 22U", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8543, "NAME": "ΠΙΝΑΚΑΣ ΕΣΩΤΕΡΙΚΟΣ 230V", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8544, "NAME": "N/B DELL VOSTRO 3550", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 8575, "NAME": "ΚΑΛΩΔΙΟ CAVEL DG 113 ΟΜΟΑΞ.", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 100},
            {"BATCH NO.": 8608, "NAME": "ΔΙΑΚΛΑΔΩΤΗΡΑΣ (SPLITTER/COMBINER) 8 PORTS", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8610, "NAME": "GLK LH SM CISCO SFP OPT. TRANSEIV.", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8611, "NAME": "H/Z PETROGEN", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8613, "NAME": "UPS ΙΚΡΙΩΜΑΤΙΚΟΥ ΤΥΠΟΥ 3KVA", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8614, "NAME": "ATTENUATORS 10DB", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8615, "NAME": "ATTENUATORS 20DB", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8617, "NAME": "ΔΟΡΥΦΟΡΙΚΟ Modem 1p-tdma mdx420", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8618, "NAME": "Terminator n plug 50 ohm", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 8},
            {"BATCH NO.": 8619, "NAME": "V-spco4 pn-dci 4way passive vsat combiner splitt", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8621, "NAME": "Smw pll 10.00 f 10khz LNB", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8625, "NAME": "ΟΜΟΑΞΟΝΙΚΟ ΚΑΛΩΔΙΟ DG 113", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8637, "NAME": "ΤΡΟΦΟΔΟΤΙΚΟ ΑΔΙΑΛ ΛΕΙΤΟΥΡ UPS", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8650, "NAME": "SG-2520 SAT PHONE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 8651, "NAME": "DC CHARGER SG-2520", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 5},
            {"BATCH NO.": 8652, "NAME": "HIGH CAPACITY BAT", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 7},
            {"BATCH NO.": 8653, "NAME": "CASE SG-2520", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
            {"BATCH NO.": 8665, "NAME": "ΒΑΣΗ ΓΙΑ THURAYA FDU2520 (06000149)", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8728, "NAME": "ΔΟΡΥΦΟΡΙΚΟ ΤΕΡΜΑΤΙΚΟ IRIDIUM 9555A", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 5},
            {"BATCH NO.": 8729, "NAME": "UP DOWN CONVERTER COMTECH", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8730, "NAME": "ΚΕΡΑΙΟΣΥΣΤΗΜΑ IRIDIUM", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 2},
            {"BATCH NO.": 8735, "NAME": "MODEM COMTECH L-BAND ETH INTERFACE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8736, "NAME": "ΔΟΡΥΦΟΡΙΚΟΙ ΕΝΙΣΧΥΤΕΣ PATRIOT KU L-BAND", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8737, "NAME": "RACK 27U ΕΠΙΔΑΠΕΔΙΟ 60Χ60 ΚΡΟΝΕ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8738, "NAME": "PANEL KIT 2 ΑΝΕΜΙΣΤ ΚΡΟΝΕ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8739, "NAME": "ΠΟΛΥΜΕΤΡΟ ΡΑΓΑΣ", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 1},
            {"BATCH NO.": 8750, "NAME": "ALGA MICROWAVE ALTX-LITE-KU-16 BUC 16W 24VDCE", "UNITS OF MEASUREMENT": "Τεμάχια", "QUANTITY": 3},
        ]


        # Create or retrieve the "Doriforika Warehouse"
        doriforika_warehouse, _ = Warehouse.objects.get_or_create(name='ΔΟΡΥΦΟΡΙΚΑ',)

        # Process each product and assign it to the group and warehouse
        for data in doriforika_products:
            product_data = {
                'batch_number': data["BATCH NO."],
                'name': data["NAME"],
                'unit_of_measurement': data["UNITS OF MEASUREMENT"],
                'category': category_kamia_epilogi,
                'usage': usage_doriforika,
                'description': ''
            }

            # Create or retrieve the product
            product, created = Product.objects.get_or_create(
                batch_number=product_data['batch_number'],
                name=product_data['name'],
                defaults={
                    'unit_of_measurement': product_data['unit_of_measurement'],
                    'category': product_data['category'],
                    'usage': product_data['usage'],
                    'description': product_data['description'],
                }
            )
            
            # Add the product to the "ΔΟΡΥΦΟΡΙΚΑ" group
            product.owners.add(group_doriforika)
            product.save()

            # Create or update the stock in the "Doriforika Warehouse"
            stock, _ = Stock.objects.get_or_create(product=product, warehouse=doriforika_warehouse, defaults={'quantity': data["QUANTITY"]})
            stock.quantity = data["QUANTITY"]
            stock.save()

        self.stdout.write(self.style.SUCCESS('Products created and assigned to ΔΟΡΥΦΟΡΙΚΑ group successfully'))
